# Generated by Django 3.1.3 on 2020-11-14 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('resumo', models.CharField(max_length=512)),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('slug', models.SlugField(blank=True, default='', max_length=64)),
                ('estado', models.IntegerField(choices=[(0, 'Não guardado'), (1, 'Rascunho'), (2, 'Aguarda moderação'), (3, 'Agendado'), (4, 'Publicado')], default=0)),
                ('img_destaque', models.ImageField(blank=True, null=True, upload_to='images/artigos', verbose_name='Imagem de destaque')),
                ('gostos', models.BigIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('artigos_relacionados', models.ManyToManyField(blank=True, related_name='_artigo_artigos_relacionados_+', to='blog.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/autores', verbose_name='Fotografia')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=64)),
                ('img', models.ImageField(upload_to='images/categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estatuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=64)),
                ('icone', models.ImageField(upload_to='images/estatutos')),
                ('pontuacao_min', models.IntegerField(default=0, verbose_name='Pontuação mínima')),
                ('pontuacao_max', models.IntegerField(default=0, verbose_name='Pontuação mínima')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('descricao', models.CharField(max_length=512)),
                ('img_destaque', models.ImageField(blank=True, null=True, upload_to='images/series', verbose_name='Imagem de destaque')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/tags')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=256)),
                ('conteudo', models.TextField(verbose_name='Texto')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, 'Não guardado'), (1, 'Rascunho'), (2, 'Aguarda moderação'), (3, 'Eliminado'), (4, 'Marcado como Spam'), (5, 'Aprovado')], default=0)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentários', to='blog.artigo')),
                ('escrito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(to='blog.Autor'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(to='blog.Categoria'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.serie'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(related_name='Tópicos', to='blog.Tag'),
        ),
    ]
