# Generated by Django 3.0.6 on 2020-05-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='artigos',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='artigos',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='artigos',
        ),
        migrations.AddField(
            model_name='artigo',
            name='artigos_relacionados',
            field=models.ManyToManyField(related_name='_artigo_artigos_relacionados_+', to='blog.Artigo'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(to='blog.Categoria'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Serie'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(related_name='Tópicos', related_query_name='Tópico', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='visitas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Visita'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografia'),
        ),
    ]
