# Generated by Django 3.0.6 on 2020-05-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artigo_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='img_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem de destaque'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='visitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Visita'),
        ),
    ]
