# Generated by Django 3.0.6 on 2020-05-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200520_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigos_relacionados',
            field=models.ManyToManyField(blank=True, null=True, related_name='_artigo_artigos_relacionados_+', to='blog.Artigo'),
        ),
    ]
