# Generated by Django 3.0.6 on 2020-05-08 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estatuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=64)),
                ('icone', models.ImageField(upload_to='')),
                ('pontuacao_min', models.IntegerField(default=0, verbose_name='Pontuação mínima')),
                ('pontuacao_max', models.IntegerField(default=0, verbose_name='Pontuação mínima')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor',
        ),
        migrations.AddField(
            model_name='artigo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Não guardado'), (1, 'Rascunho'), (2, 'Aguarda moderação'), (3, 'Agendado'), (4, 'Publicado')], default=0),
        ),
        migrations.AddField(
            model_name='artigo',
            name='gostos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artigo',
            name='img_destaque',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem de destaque'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=256, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('img', models.ImageField(upload_to='')),
                ('artigos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('descricao', models.CharField(max_length=512)),
                ('img_destaque', models.ImageField(upload_to='', verbose_name='Imagem de destaque')),
                ('artigos', models.ManyToManyField(to='blog.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=256)),
                ('texto', models.CharField(max_length=1024)),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, 'Não guardado'), (1, 'Rascunho'), (2, 'Aguarda moderação'), (3, 'Eliminado'), (4, 'Marcado como Spam'), (5, 'Aprovado')], default=0)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', related_query_name='person', to='blog.Artigo')),
                ('escrito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=64)),
                ('img', models.ImageField(upload_to='')),
                ('artigos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Artigo')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(to='blog.Utilizador'),
        ),
    ]
